version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  apt_packages:
    - xvfb

conda:
  environment: .rtd-environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

python:
   install:
     - method: pip
       extra_requirements:
        - all
        - docs
       path: .
