name: Build and Deploy Docs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
      PYVISTA_OFF_SCREEN: True
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[docs]
    - name: Setup Server
      run: bash .github/workflows/setup_headless_display.sh
    - name: Build docs
      run: |
        cd docs
        make html
    - name: Add .nojekyll to bypass gh-pages
      run: touch docs/_build/html/.nojekyll
    - name: Deploy docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs/_build/html
        single-commit: true
        clean: true
